name: Minecraft Bedrock Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y curl unzip rsync
    - name: Install Minecraft Server
      run: |
        mkdir server
        curl -o server/bedrock-server.zip https://minecraft.azureedge.net/bin-linux/bedrock-server-1.19.62.01.zip
        cd server
        unzip bedrock-server.zip
        chmod +x bedrock_server
    - name: Synchronize server with repository
      run: |
        rsync -avz --exclude=world/server.properties --exclude=world/permissions.json --exclude=world/whitelist.json server/ $GITHUB_WORKSPACE/
    - name: Start Minecraft Server
      run: |
        nohup bash -c "cd server && LD_LIBRARY_PATH=. ./bedrock_server" > /dev/null 2>&1 &
    - name: Backup Minecraft Server
      run: |
        while true; do
          cd server
          zip -r backup_$(date +"%Y-%m-%d_%H-%M-%S").zip world
          cd $GITHUB_WORKSPACE
          git add .
          git commit -m "Sync server files"
          git push
          sleep 300
        done
      continue-on-error: true
