name: Minecraft Bedrock Server

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  SERVER_DIR: server
  BACKUP_DIR: backup

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl unzip git-lfs
        git-lfs install --skip-smudge
    - name: Install Minecraft Server
      run: |
        mkdir $SERVER_DIR
        cd $SERVER_DIR
        curl -o bedrock-server.zip https://minecraft.azureedge.net/bin-linux/bedrock-server-1.19.62.01.zip
        unzip bedrock-server.zip
        chmod +x bedrock_server
    - name: Start Minecraft Server
      run: |
        cd $SERVER_DIR
        LD_LIBRARY_PATH=. ./bedrock_server
    - name: Backup Minecraft Server
      run: |
        mkdir $BACKUP_DIR
        while true; do
          cd $SERVER_DIR
          tar -czf $BACKUP_DIR/backup_$(date +"%Y-%m-%d_%H-%M-%S").tar.gz world
          cd $BACKUP_DIR
          ls -t | tail -n +6 | xargs rm --
          sleep 300
        done &
        disown
    - name: Keep Minecraft Server Running
      run: |
        while true; do
          cd $SERVER_DIR
          git add .
          git commit -m "Auto-commit at $(date +'%Y-%m-%d %H:%M:%S')"
          git push
          sleep 60
        done &
        disown
