name: Minecraft Bedrock Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y curl unzip
    - name: Install Minecraft Server
      run: |
        mkdir server
        curl -o server/bedrock-server.zip https://minecraft.net/en-us/download/server/bedrock/
        cd server
        unzip bedrock-server.zip
        chmod +x bedrock_server
    - name: Start Minecraft Server
      run: cd server && LD_LIBRARY_PATH=. ./bedrock_server

