name: Minecraft Bedrock Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y curl unzip screen
    - name: Install Minecraft Server
      run: |
        mkdir server
        curl -o server/bedrock-server.zip https://minecraft.azureedge.net/bin-linux/bedrock-server-1.19.62.01.zip
        cd server
        unzip bedrock-server.zip
        chmod +x bedrock_server
    - name: Start Minecraft Server
      run: screen -d -m cd server && LD_LIBRARY_PATH=. ./bedrock_server
